"use client";

import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import HistoryPanel from "@/components/HistoryPanel";
import { useAmbulances } from "@/hooks/useAmbulances";
import type { AmbulanceReading } from "@/types";

const AmbulanceMap = dynamic(() => import("@/components/AmbulanceMap"), { ssr: false, loading: () => <div className="h-full min-h-[430px] animate-pulse bg-slate-100" /> });
type View = "command" | "traffic" | "hospital" | "diagnostics" | "settings";
type MapFocus = "all" | "selected";
const navItems: { id: View; label: string; icon: string }[] = [{ id: "command", label: "Command center", icon: "⌖" }, { id: "traffic", label: "Traffic control", icon: "↗" }, { id: "hospital", label: "Hospital view", icon: "+" }, { id: "diagnostics", label: "Device diagnostics", icon: "▣" }, { id: "settings", label: "Settings", icon: "⚙" }];
function relativeTime(createdAt: string, now: number | null) { if (now === null) return "updating…"; const seconds = Math.max(0, Math.floor((now - new Date(createdAt).getTime()) / 1000)); return seconds < 8 ? "just now" : seconds < 60 ? `${seconds}s ago` : `${Math.floor(seconds / 60)}m ago`; }
function Metric({ label, value, detail, icon }: { label: string; value: React.ReactNode; detail: string; icon: string }) { return <article className="metric-card"><div className="metric-icon metric-symbol">{icon}</div><div><p className="eyebrow">{label}</p><p className="metric-value">{value}</p><p className="metric-detail">{detail}</p></div></article>; }
function LocalClock() { const [time, setTime] = useState("—"); useEffect(() => { const update = () => setTime(new Intl.DateTimeFormat(undefined, { hour: "2-digit", minute: "2-digit" }).format(new Date())); update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer); }, []); return <time>{time}</time>; }

export default function Home() {
  const { ambulances, connectionStatus } = useAmbulances();
  const [view, setView] = useState<View>("command");
  const [selectedAmbulanceId, setSelectedAmbulanceId] = useState<string | null>(null);
  const [historyAmbulance, setHistoryAmbulance] = useState<AmbulanceReading | null>(null);
  const [mapFocus, setMapFocus] = useState<MapFocus>("all");
  const [mapFocusVersion, setMapFocusVersion] = useState(0);
  const [now, setNow] = useState<number | null>(null);
  const [follow, setFollow] = useState(true);
  const [priorityRequested, setPriorityRequested] = useState(false);
  const [hospitalReady, setHospitalReady] = useState(false);
  const [demoMode, setDemoMode] = useState(true);
  useEffect(() => { const update = () => setNow(Date.now()); update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { setSelectedAmbulanceId((current) => current && ambulances.some((ambulance) => ambulance.ambulance_id === current) ? current : ambulances[0]?.ambulance_id ?? null); }, [ambulances]);

  const unit = ambulances.find((ambulance) => ambulance.ambulance_id === selectedAmbulanceId) ?? null;
  const online = connectionStatus === "connected";
  const emergency = unit?.status.toLowerCase() === "emergency";
  const lastPacket = unit ? relativeTime(unit.created_at, now) : "waiting";
  const activeName = navItems.find((item) => item.id === view)?.label ?? "Command center";
  const selectAmbulance = (ambulanceId: string) => { setSelectedAmbulanceId(ambulanceId); setMapFocus("selected"); };
  const focusAll = () => { setMapFocus("all"); setMapFocusVersion((current) => current + 1); };
  const selector = <section className="ambulance-selector"><div className="selector-heading"><p className="eyebrow">Ambulances</p><button className={`all-ambulances ${mapFocus === "all" ? "active" : ""}`} onClick={focusAll}>All ambulances</button></div><div className="ambulance-list">{ambulances.length ? ambulances.map((ambulance) => <button key={ambulance.ambulance_id} className={`ambulance-option ${ambulance.ambulance_id === selectedAmbulanceId ? "active" : ""}`} onClick={() => selectAmbulance(ambulance.ambulance_id)}><span><strong>{ambulance.ambulance_id}</strong><small>{ambulance.people} {ambulance.people === 1 ? "person" : "people"}</small></span><em className={ambulance.status.toLowerCase() === "emergency" ? "status-emergency" : "status-normal"}>{ambulance.status}</em></button>) : <p className="selector-empty">No ambulance telemetry received yet.</p>}</div></section>;

  const commandCenter = <><section className="status-strip"><div><p className="eyebrow">Unit status</p><strong>{unit?.ambulance_id ?? "Awaiting unit"}</strong></div>{unit && <span className={`emergency ${emergency ? "" : "normal"}`}><i />{emergency ? "Emergency" : unit.status}</span>}<span className="packet">Last packet: {lastPacket}</span><span className="demo">{demoMode ? "Demo mode" : "Live mode"}</span></section><section className="main-grid"><article className="map-card"><div className="card-head"><div><h2>Live location</h2><p>OpenStreetMap · GPS tracking</p></div><span className="live"><i />Live</span></div><div className="map-area"><AmbulanceMap ambulances={ambulances} selectedAmbulanceId={mapFocus === "selected" ? selectedAmbulanceId : null} focusVersion={mapFocusVersion} onAmbulanceSelect={selectAmbulance} /></div><div className="map-controls"><button aria-label="Play route">▶</button><span className="route" /><span>Live route playback</span><button className="follow" onClick={() => setFollow(!follow)}>{follow ? "Following unit" : "Follow unit"}</button></div></article><section className="details">{selector}<button className="unit-card" onClick={() => unit && setHistoryAmbulance(unit)}><div className="metric-icon metric-symbol">✚</div><div><p className="eyebrow">Ambulance ID</p><p className="unit-id">{unit?.ambulance_id ?? "—"}</p><span>{unit ? "View route history →" : "Telemetry will appear here"}</span></div></button><Metric icon="◉" label="People inside" value={unit?.people ?? "—"} detail="Live sensor value" /><Metric icon="⌖" label="GPS coordinates" value={unit ? `${unit.latitude.toFixed(5)}, ${unit.longitude.toFixed(5)}` : "—"} detail="Latitude · longitude" /><Metric icon="↗" label="Speed" value="— km/h" detail="Not reported by device" /><Metric icon="◷" label="Last update" value={lastPacket} detail={unit && now ? new Date(unit.created_at).toLocaleTimeString() : "Awaiting telemetry"} /><div className="mini"><Metric icon="▰" label="Battery" value="—%" detail="Not reported" /><Metric icon="▮" label="Signal" value={online ? "Good" : "—"} detail={online ? "Live connection" : "Reconnecting"} /></div></section></section><section className="bottom"><Metric icon="▣" label="Device" value="ESP32" detail={online ? "Online · Wi-Fi" : "Offline · Wi-Fi"} /><Metric icon="◎" label="Accuracy" value="— m" detail="GPS precision unavailable" /><Metric icon="</>" label="API channel" value={online ? "Connected" : "Connecting"} detail={online ? "Authenticated · live stream" : "Checking connection"} /></section></>;
  const traffic = <section className="panel-grid"><article className="wide-panel"><p className="eyebrow">Traffic control</p><h2>Priority corridor</h2><p className="panel-copy">Coordinate a clear route for the selected emergency vehicle. Traffic-light integration is simulated in demo mode.</p><div className="control-row"><button className="primary-button" onClick={() => setPriorityRequested(!priorityRequested)}>{priorityRequested ? "Priority requested" : "Request signal priority"}</button><span className={priorityRequested ? "success-text" : "muted-text"}>{priorityRequested ? "Corridor request queued" : "No active corridor request"}</span></div></article><Metric icon="↗" label="Selected route" value={unit ? "GPS active" : "Waiting"} detail={unit ? `Tracking ${unit.ambulance_id}` : "No route available yet"} /><Metric icon="!" label="Road alerts" value="0" detail="No reported obstructions" /></section>;
  const hospital = <section className="panel-grid"><article className="wide-panel"><p className="eyebrow">Hospital view</p><h2>Incoming patient readiness</h2><p className="panel-copy">Share the selected unit status with the receiving hospital and prepare the emergency team.</p><div className="control-row"><button className="primary-button" onClick={() => setHospitalReady(!hospitalReady)}>{hospitalReady ? "Hospital marked ready" : "Mark receiving team ready"}</button><span className={hospitalReady ? "success-text" : "muted-text"}>{hospitalReady ? "Receiving team notified" : "Waiting for hospital confirmation"}</span></div></article><Metric icon="✚" label="Incoming unit" value={unit?.ambulance_id ?? "—"} detail={emergency ? "Emergency triage" : "Unit status pending"} /><Metric icon="◉" label="Occupancy" value={unit?.people ?? "—"} detail="Reported people inside" /></section>;
  const diagnostics = <section className="panel-grid"><Metric icon="▣" label="Controller" value="ESP32" detail={online ? "Online · Wi-Fi connected" : "Connection unavailable"} /><Metric icon="◎" label="GPS" value={unit ? "Receiving" : "Waiting"} detail={unit ? `Coordinates from ${unit.ambulance_id}` : "No GPS packet yet"} /><Metric icon="▮" label="Network" value={online ? "Connected" : "Disconnected"} detail={online ? "WebSocket live stream" : "Automatic retry enabled"} /><Metric icon="◷" label="Last packet" value={lastPacket} detail="Selected ambulance telemetry" /></section>;
  const settings = <section className="settings-panel"><p className="eyebrow">Settings</p><h2>Dashboard preferences</h2><label className="setting-row"><span><strong>Demo mode</strong><small>Show demo labels for simulated controls.</small></span><button className={`toggle ${demoMode ? "on" : ""}`} onClick={() => setDemoMode(!demoMode)} aria-pressed={demoMode}><i /></button></label><label className="setting-row"><span><strong>Live location follow</strong><small>Keep the map centered on selected unit positions.</small></span><button className={`toggle ${follow ? "on" : ""}`} onClick={() => setFollow(!follow)} aria-pressed={follow}><i /></button></label><p className="settings-note">Connection URLs and data collection are configured in the project environment file.</p></section>;
  const viewContent: Record<View, React.ReactNode> = { command: commandCenter, traffic, hospital, diagnostics, settings };
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-icon">✚</div><div><strong>Smart Ambulance</strong><span>IoT Monitoring</span></div></div><p className="nav-label">Operations</p><nav>{navItems.map((item) => <button key={item.id} className={`nav-item ${view === item.id ? "active" : ""}`} onClick={() => setView(item.id)}><span className="nav-symbol">{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-foot"><i className={`dot ${online ? "" : "offline"}`} />System {online ? "operational" : "reconnecting"}</div></aside><section className="workspace"><header className="topbar"><div><p className="breadcrumb">{activeName}</p><h1>{view === "command" ? "Live emergency overview" : activeName}</h1></div><div className="top-actions"><span className={`network ${online ? "" : "network-offline"}`}><i />Network {online ? "online" : "offline"}</span><LocalClock /><button className="icon-button" aria-label="Notifications">♧</button></div></header><div className="content">{viewContent[view]}</div></section>{historyAmbulance && <HistoryPanel ambulance={historyAmbulance} onClose={() => setHistoryAmbulance(null)} />}</main>;
}
